export const UPDATE_TOTAL_DONATE = 'UPDATE_TOTAL_DONATE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const FETCH_DONATION_SUCCESS = 'FETCH_DONATION_SUCCESS';
export const FETCH_DONATION_FAIL = 'FETCH_DONATION_FAIL';
export const FETCH_DONATION_START = 'FETCH_DONATION_START';
